name: Lint & Format

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run ESLint (check and fix)
      - name: Run ESLint
        run: |
          npm run lint
          npm run lint:fix

      # Run Prettier (check and format)
      - name: Run Prettier
        run: |
          npm run format:check
          npm run format:write
